export const FETCH_INGREDIENTLISTITEMS_BY_RECIPE = 'FETCH_INGREDIENTLISTITEMS_BY_RECIPE';
export const GET_SELECTED_INGREDIENTLISTITEM = 'GET_SELECTED_INGREDIENTLISTITEM';
export const SET_SELECTED_INGREDIENTLISTITEM = 'GET_SELECTED_INGREDIENTLISTITEM';
export const NEW_INGREDIENTLISTITEM = 'NEW_INGREDIENTLISTITEM';
export const NEW_INGREDIENTLISTITEMS = 'NEW_INGREDIENTLISTITEMS';
export const EDIT_INGREDIENTLISTITEM = "EDIT_INGREDIENTLISTITEM";
export const DELETE_INGREDIENTLISTITEM = 'DELETE_INGREDIENTLISTITEM';