export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const GET_SELECTED_INGREDIENT = 'GET_SELECTED_INGREDIENT';
export const SET_SELECTED_INGREDIENT = 'GET_SELECTED_INGREDIENT';
export const NEW_INGREDIENT = 'NEW_INGREDIENT';
export const EDIT_INGREDIENT = "EDIT_INGREDIENT";
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';