export const ADD_RECIPES_TO_SHOPPINGLIST = 'ADD_RECIPES_TO_SHOPPINGLIST';
export const GET_RECIPES_BY_SHOPPINGLIST = 'GET_RECIPES_BY_SHOPPINGLIST';
export const SET_SELECTED_SHOPPINGLIST = 'SET_SELECTED_SHOPPINGLIST';